# IMAP connection settings
imap:
    # Default timeout for IMAP connections (in seconds)
    default_timeout: 30

# Email processing options
email_processing:
    # Max size for media uploads in bytes (25 MiB default)
    max_upload_bytes: 26214400
    # Attempt gzip for oversized original HTML/text bodies before attaching
    gzip_large_bodies: true
